### ISSUE TITLE
Genetic algorithm models

### ISSUE THREAD

**Issue by rspadim** [dynamicslab/pysindy#79] opened 2020-06-20 10:47 UTC
## Is your feature request related to a problem? Please describe.
Could be possible extend lib with nonlinear genetic algorithms to discover non linear patterns? There’re some python libs today that could help

## Describe the solution you'd like
Research some genetic methods, implement them

## Describe alternatives you've considered
Implement a base generic example of model that will be used to fit a genetic algorithm “fitter”

**Comment by rspadim** [comment] 2020-06-20 10:49
https://gplearn.readthedocs.io/en/stable/

https://deap.readthedocs.io/en/master/examples/gp_symbreg.html

https://github.com/topics/symbolic-regression

https://github.com/cfusting/fast-symbolic-regression

https://towardsdatascience.com/symbolic-regression-and-genetic-programming-8aed39e7f030

**Comment by briandesilva** [comment] 2020-06-23 17:58
Thanks for your suggestion (and for the sources)! I like this idea in principle, but the SINDy framework was introduced as an alternative to other model discovery techniques. Because PySINDy formulates model discovery as a sparse regression problem, it would be difficult to adapt the package to accommodate genetic algorithms. PySINDy isn't meant to be a catch-all model discovery package, rather it aims to provide a quality implementation of the SINDy method.

**Comment by rspadim** [comment] 2020-06-23 18:02
nice :), i'm new here, but i liked the code and i'm testing it

**Comment by briandesilva** [comment] 2020-06-23 18:06
Welcome! I'm glad you're enjoying the package. Feel free to keep creating issues with any ideas you have for how to improve PySINDy. I'm going to close this one now.

**Closed by briandesilva** 2020-06-23 18:06 UTC
