### ISSUE TITLE
[BUG] Failure when running example

### ISSUE THREAD

**Issue by Jancwind** [dynamicslab/pysindy#125] opened 2021-09-27 06:48 UTC
I  met a bug when running a simple example, and the message was:

File "D:\study\software\anaconda3\envs\sindy\lib\site-packages\pysindy\feature_library\polynomial_library.py", line 170, in fit
    self.n_input_features_ = n_features
AttributeError: can't set attribute

What's the problem?

**Comment by Jancwind** [comment] 2021-09-27 11:27
> #124
> 
> I have experienced a similar error. This is because you are using Scikit-learn 1.0, right?
> If so , try to downgrade:
> 
> ```
> pip install 'scikit-learn<1'
> ```

Yes, the problem is exactly caused by the version of scikit-learn. Earlier today I also tried your suggestion, and after downgrading, it worked. But thank you very much!

**Comment by akaptano** [comment] 2021-09-27 15:04
Could you provide the full code you are running. From the one line, this actually looks like the "correct" behavior, in the sense that self.n_input_features_ should be presumably be set when the call to the library initializer is made (i.e. PolynomialLibrary() or something). Since this is a class variable, it would be better code to keep it private, meaning it should indeed complain if you try to set it directly.

**Comment by A3EKV** [comment] 2021-09-27 20:49
@akaptano 
Try to upgrade to the latest version of Scikit-learn and run the first jupyter notebook  `1_feature_overview.ipynb` in the examples folder. You will get the same error.

**Comment by akaptano** [comment] 2021-09-28 00:01
Agreed, this is a legitimate bug. I'll try to see if there is an update to the code that works for scikit-learn version >= 1.0 but still maintains the backward capability. Thanks for bringing this up and let's close this issue for now while I work on it in issue #124

**Closed by akaptano** 2021-09-28 00:01 UTC

**Comment by akaptano** [comment] 2021-09-28 20:43
Fixed this in the new release. Hopefully will get this out in a few weeks. For future reference, the issue is that scikit-learn 1.0 and beyond has decided that self.n_inputs_features_ should be called self.n_features_in_ so the fix is we have to check the scikit-learn version whenever assigning this variable for now.
