### ISSUE TITLE
When installing with pip it fails to find libmkl [BUG]

### ISSUE THREAD

**Issue by a-berg** [dynamicslab/pysindy#137] opened 2021-12-07 08:34 UTC
### Reproducing code example:

```
pip install pysindy
[...]
Successfully installed cvxpy-1.1.17 derivative-0.3.1 pysindy-1.5.1
```

```python
import pysindy
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/pysindy/__init__.py", line 11, in <module>
    from . import optimizers
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/pysindy/optimizers/__init__.py", line 2, in <module>
    from .constrained_sr3 import ConstrainedSR3
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/pysindy/optimizers/constrained_sr3.py", line 3, in <module>
    import cvxpy as cp
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/__init__.py", line 27, in <module>
    from cvxpy.problems.problem import Problem
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 35, in <module>
    from cvxpy.reductions import InverseData
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/reductions/__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 21, in <module>
    from cvxpy.reductions.solvers import defines as slv_def
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/reductions/solvers/defines.py", line 98, in <module>
    INSTALLED_SOLVERS = installed_solvers()
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/reductions/solvers/defines.py", line 87, in installed_solvers
    if solver.is_installed():
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/reductions/solvers/solver.py", line 59, in is_installed
    self.import_solver()
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 144, in import_solver
    import scs
  File "<HOME>/miniconda3/envs/<ENV>/lib/python3.7/site-packages/scs/__init__.py", line 5, in <module>
    import _scs_direct
ImportError: libmkl_rt.so.1: cannot open shared object file: No such file or directory
```

### PySINDy/Python version information:

Python version: 3.7.11
PySINDy version: 1.5.1

### Additional information

When installing with conda (PySINDy 1.3), the package fails to `fit` the model due to an incompatibility with scikit-learn 1.0 (`n_input_features_` has been removed and you need to use `n_features_in_`).
The package is non-functional on my machine either way.

**Comment by akaptano** [comment] 2021-12-07 16:36
my guess so far is that the more recent SCS package needs MKL support, so you might try downgrading. But let me know your version so I can try reproducing.

**Comment by a-berg** [comment] 2021-12-09 10:52
Thank you akaptano, the SCS version is 2.1.4. I noticed the other bug was already known and fixed so it's not a concern for me anymore, if I get this version to work.
There's something else: I was able to make it work in a google collab, so maybe the problem is with my conda env. I will try to

- Create new local conda environment and install pysindy
- Downgrade SCS in current environment

And report back.

**Comment by akaptano** [comment] 2021-12-09 19:18
It looks like I cannot even successfully build SCS version 2.1.4 on my computer without MKL. I have version 2.1.2 and it works fine. Let me know if downgrading works.

**Comment by a-berg** [comment] 2021-12-10 11:45
Yes, it worked!

**Comment by akaptano** [comment] 2021-12-13 16:55
Great to hear. I will keep this issue open because it seems to be associated with the newest version of SCS. If this starts coming up frequently for users, we will consider making the default SCS installation <= 2.1.2 for PySINDy, or some other fix.

**Comment by a-berg** [comment] 2021-12-14 13:44
I understand. Thank you anyway, it's good to see that the project has such active devs!

**Comment by akaptano** [comment] 2022-01-06 17:05
Closing this now. We have added SCS<=2.1.4 to requirements-dev.txt for now (in the new release v1.6).

**Closed by akaptano** 2022-01-06 17:05 UTC
Labels: bug
