### ISSUE TITLE
NaN, infinity for dtype float64 when using model.simulate()

### ISSUE THREAD

**Issue by okamel1** [dynamicslab/pysindy#96] opened 2020-10-19 14:12 UTC
I am using PySINDy with a model with 20 states and 2 inputs trying to identify the dynamical system of this dataset. The model was successfully identified using polynomial library of 3rd degree and STLSQ optimizer with a score of 0.975. I checked the derivatives and they look perfect compared to the ground truth. 
Afterwards, I tried to simulate my model forward in time but I get the following error.

I tried to use another type of integrators from scipy.integrate but my trials failed.

### Reproducing code example:

```python
import pysindy as ps
stlsq_optimizer = ps.STLSQ(threshold=.01, alpha=10, max_iter=100, normalize=True)
poly_library = ps.PolynomialLibrary(degree=3, include_interaction=True)
model_nonlinear = ps.SINDy(optimizer=stlsq_optimizer, feature_library=poly_library)
model_nonlinear.fit(x=x_NL_train, x_dot=x_dot_NL_train, u=u_f_train, t=dt)
x_NL_test_sim = model_nonlinear.simulate(np.array(x_NL_test[0,:]), np.array(t_test), f_interp)
```

### Error message:

Traceback (most recent call last)
<ipython-input-157-50267c59b1f1> in <module>
----> 1 x_NL_test_sim = model_nonlinear.simulate(np.array(x_NL_test[0,:]), np.array(t_test), f_interp)

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\pysindy\pysindy.py in simulate(self, x0, t, u, integrator, stop_condition, **integrator_kws)
    712                         return self.predict(x[newaxis, :], u(t))[0]
    713 
--> 714             return integrator(rhs, x0, t, **integrator_kws)
    715 
    716     @property

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\scipy\integrate\odepack.py in odeint(func, y0, t, args, Dfun, col_deriv, full_output, ml, mu, rtol, atol, tcrit, h0, hmax, hmin, ixpr, mxstep, mxhnil, mxordn, mxords, printmessg, tfirst)
    242                              full_output, rtol, atol, tcrit, h0, hmax, hmin,
    243                              ixpr, mxstep, mxhnil, mxordn, mxords,
--> 244                              int(bool(tfirst)))
    245     if output[-1] < 0:
    246         warning_msg = _msgs[output[-1]] + " Run with full_output = 1 to get quantitative information."

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\pysindy\pysindy.py in rhs(x, t)
    705 
    706                     def rhs(x, t):
--> 707                         return self.predict(x[newaxis, :], u(t).reshape(1, -1))[0]
    708 
    709                 else:

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\pysindy\pysindy.py in predict(self, x, u, multiple_trajectories)
    357                 x = validate_input(x)
    358                 u = validate_control_variables(x, u)
--> 359                 return self.model.predict(concatenate((x, u), axis=1))
    360 
    361     def equations(self, precision=3):

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\metaestimators.py in <lambda>(*args, **kwargs)
    117 
    118         # lambda, but not partial, allows help() to work with update_wrapper
--> 119         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
    120         # update the docstring of the returned function
    121         update_wrapper(out, self.fn)

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\pipeline.py in predict(self, X, **predict_params)
    406         for _, name, transform in self._iter(with_final=False):
    407             Xt = transform.transform(Xt)
--> 408         return self.steps[-1][-1].predict(Xt, **predict_params)
    409 
    410     @if_delegate_has_method(delegate='_final_estimator')

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\pysindy\optimizers\sindy_optimizer.py in predict(self, x)
     83 
     84     def predict(self, x):
---> 85         prediction = self.optimizer.predict(x)
     86         if prediction.ndim == 1:
     87             return prediction[:, np.newaxis]

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\linear_model\_base.py in predict(self, X)
    234             Returns predicted values.
    235         """
--> 236         return self._decision_function(X)
    237 
    238     _preprocess_data = staticmethod(_preprocess_data)

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\linear_model\_base.py in _decision_function(self, X)
    216         check_is_fitted(self)
    217 
--> 218         X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
    219         return safe_sparse_dot(X, self.coef_.T,
    220                                dense_output=True) + self.intercept_

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    644         if force_all_finite:
    645             _assert_all_finite(array,
--> 646                                allow_nan=force_all_finite == 'allow-nan')
    647 
    648     if ensure_min_samples > 0:

C:\Users\kamel\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
     98                     msg_err.format
     99                     (type_err,
--> 100                      msg_dtype if msg_dtype is not None else X.dtype)
    101             )
    102     # for object dtype data, we only check for NaNs (GH-13254)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64')
### PySINDy/Python version information:

PySINDy: 1.1.0
Python: 3.7.7

**Comment by akaptano** [comment] 2020-10-19 14:51
Omar, could you post the particular model you are getting, and the ground truth model? My guess is that your model has small numerical errors on the coefficients, meaning that instability will occur when you numerically integrate the equations. Also, I have never seen anyone try and model a system as large as a 20-dimensional state space with 2 control inputs with SINDy -- this will be interesting to see how we can help. Unfortunately a system this large may be intractable for an analytic nonlinear stability analysis.

**Comment by okamel1** [comment] 2020-10-19 15:06
Hi Alan,
Actually I am trying to hit the limits of PySINDy as my problem involves models with tens of DOFs. I have to reduce the dimensionality of my data using e.g. PCA and then use PySINDy to identify a model in this reduced space.

My model is:
`x0' = 10216.587 x1 + 778.887 x2 + -46060.093 x3 + 22279.147 x4 + 6647.290 x5 + 24178.390 x6 + 38882.123 x7 + -49673.532 x8 + -50612.664 x9 + 28274.161 x10 + -2216.165 x11 + 4385.553 x12 + 33987.874 x13 + 26327.517 x14 + -44305.162 x15 + -33585.530 x16 + 11027.608 x17 + 36827.184 x18 + -17370.516 x19 + -0.113 u1 + 0.097 x0 u1 + 1357.710 x1 u1 + -4291.939 x2 u1 + 4650.203 x3 u1 + -1872.958 x4 u1 + 156.890 x5 u1 + 7180.303 x11 u0 + -15373.310 x12 u0 + -917.895 x13 u0 + 15891.559 x14 u0 + 4056.632 x15 u0 + -18321.138 x16 u0 + 7483.755 x17 u0 + -0.025 x0 u0 u1 + -0.108 x0 u1^2 + 1.487 x4 u0 u1 + 194.669 x5 u1^2 + -219.926 x6 u1^2 + -320.754 x7 u1^2 + 212.273 x8 u1^2 + 472.490 x9 u1^2 + -341.626 x10 u1^2 + 186.859 x15 u0^2 + -353.637 x16 u0^2 + -102.627 x17 u0 u1 + 316.475 x18 u0^2 + 186.257 x18 u0 u1 + -149.672 x19 u0^2 + -84.985 x19 u0 u1 + 2.983 x19 u1^2
x1' = 9283.876 x1 + -12686.560 x2 + -13450.003 x3 + 16177.527 x4 + 4944.749 x5 + 4562.484 x6 + 2647.997 x7 + -12501.786 x8 + -4254.708 x9 + -5847.675 x10 + -236.234 x11 + 13707.105 x12 + 10890.041 x13 + -7606.599 x14 + -29.039 x15 + -3826.014 x16 + -28712.564 x17 + 41090.282 x18 + -14163.283 x19 + -0.104 u1 + 2921.841 x7 u0 + -7072.918 x8 u0 + 4384.260 x9 u0 + -1068.847 x17 u0 + 1037.677 x18 u0 + -202.011 x19 u0 + 0.001 x0 u0 u1 + 275.601 x14 u0^2 + -650.771 x15 u0^2 + 0.225 x16 u0 u1 + 1169.651 x17 u0^2 + -0.339 x17 u0 u1 + -1113.190 x18 u0^2 + 318.708 x19 u0^2 + 0.113 x19 u0 u1
x2' = 8071.786 x1 + -9181.830 x2 + -18190.381 x3 + 21420.406 x4 + 3262.046 x5 + 722.240 x6 + 3084.740 x7 + -9518.179 x8 + -2958.373 x9 + -6847.892 x10 + -1518.611 x11 + 13517.597 x12 + 11525.420 x13 + -8444.291 x14 + -1194.922 x15 + 3.138 x16 + -29905.745 x17 + 39513.653 x18 + -13371.201 x19 + -0.104 u1 + 2872.379 x7 u0 + -6959.466 x8 u0 + 4318.588 x9 u0 + -1089.886 x17 u0 + 1081.994 x18 u0 + -223.609 x19 u0 + 0.001 x0 u0 u1 + 269.382 x14 u0^2 + -635.810 x15 u0^2 + 0.250 x16 u0 u1 + 1141.817 x17 u0^2 + -0.374 x17 u0 u1 + -1086.281 x18 u0^2 + 310.892 x19 u0^2 + 0.124 x19 u0 u1
x3' = 7616.407 x1 + -5806.928 x2 + -23239.320 x3 + 19930.559 x4 + 6273.508 x5 + 5338.183 x6 + -1353.739 x7 + -3062.104 x8 + -12452.402 x9 + -6037.252 x10 + 554.942 x11 + 13063.045 x12 + 12413.073 x13 + -1477.085 x14 + -10285.577 x15 + -5907.020 x16 + -14274.914 x17 + 30454.679 x18 + -11758.450 x19 + -0.104 u1 + 8.891 x7 u0 + -10.469 x8 u0 + 9.047 x18 u0 + -7.469 x19 u0 + 0.001 x0 u0 u1 + 109.404 x14 u0^2 + -239.238 x15 u0^2 + -0.164 x16 u0 u1 + 360.256 x17 u0^2 + 0.230 x17 u0 u1 + -309.640 x18 u0^2 + 79.216 x19 u0^2 + -0.067 x19 u0 u1
x4' = 6615.732 x1 + -4512.471 x2 + -22249.638 x3 + 19917.882 x4 + 4866.539 x5 + 3677.996 x6 + -1318.867 x7 + -1593.327 x8 + -10884.743 x9 + -5653.510 x10 + -40.557 x11 + 11751.824 x12 + 11364.697 x13 + -1716.940 x14 + -9208.753 x15 + -4117.425 x16 + -14052.936 x17 + 27703.292 x18 + -10559.182 x19 + -0.104 u1 + 8.670 x7 u0 + -10.194 x8 u0 + 8.699 x18 u0 + -7.175 x19 u0 + 0.001 x0 u0 u1 + 107.340 x14 u0^2 + -234.906 x15 u0^2 + -0.120 x16 u0 u1 + 354.537 x17 u0^2 + 0.166 x17 u0 u1 + -305.228 x18 u0^2 + 78.256 x19 u0^2 + -0.047 x19 u0 u1
x5' = 4988.464 x1 + -4397.069 x2 + -16854.368 x3 + 21435.372 x4 + -118.611 x5 + -3525.469 x6 + 2805.572 x7 + -5162.605 x8 + 832.819 x9 + -5759.539 x10 + -2983.714 x11 + 9816.363 x12 + 8759.609 x13 + -8128.492 x14 + 170.847 x15 + 4450.047 x16 + -27162.923 x17 + 30709.824 x18 + -9886.502 x19 + -0.104 u1 + 2670.819 x7 u0 + -6508.286 x8 u0 + 4066.093 x9 u0 + -1244.085 x17 u0 + 1370.871 x18 u0 + -355.412 x19 u0 + 0.001 x0 u0 u1 + 234.939 x14 u0^2 + -552.719 x15 u0^2 + 0.314 x16 u0 u1 + 986.315 x17 u0^2 + -0.468 x17 u0 u1 + -935.497 x18 u0^2 + 266.961 x19 u0^2 + 0.154 x19 u0 u1
x6' = 3775.523 x1 + -2492.257 x2 + -16396.897 x3 + 21484.529 x4 + -1417.437 x5 + -5218.219 x6 + 2686.379 x7 + -3442.705 x8 + 2306.832 x9 + -5324.913 x10 + -3536.038 x11 + 8341.893 x12 + 7663.839 x13 + -7965.753 x14 + 623.868 x15 + 6217.402 x16 + -25933.669 x17 + 27082.122 x18 + -8464.861 x19 + -0.104 u1 + 2579.260 x7 u0 + -6301.491 x8 u0 + 3948.881 x9 u0 + -1302.539 x17 u0 + 1483.764 x18 u0 + -407.875 x19 u0 + 0.001 x0 u0 u1 + 219.479 x14 u0^2 + -515.510 x15 u0^2 + 0.328 x16 u0 u1 + 916.957 x17 u0^2 + -0.489 x17 u0 u1 + -868.353 x18 u0^2 + 247.426 x19 u0^2 + 0.160 x19 u0 u1
x7' = 2528.798 x1 + -521.824 x2 + -15930.350 x3 + 21484.245 x4 + -2736.572 x5 + -6907.019 x6 + 2575.485 x7 + -1675.839 x8 + 3758.797 x9 + -4880.900 x10 + -4079.463 x11 + 6825.977 x12 + 6544.902 x13 + -7758.135 x14 + 1044.857 x15 + 7985.626 x16 + -24578.699 x17 + 23304.010 x18 + -6994.248 x19 + -0.103 u1 + 2471.436 x7 u0 + -6054.999 x8 u0 + 3806.822 x9 u0 + -1353.055 x17 u0 + 1587.746 x18 u0 + -457.950 x19 u0 + 0.001 x0 u0 u1 + 202.711 x14 u0^2 + -475.225 x15 u0^2 + 0.339 x16 u0 u1 + 842.113 x17 u0^2 + -0.505 x17 u0 u1 + -796.005 x18 u0^2 + 226.405 x19 u0^2 + 0.165 x19 u0 u1
x8' = 1295.060 x1 + 1451.642 x2 + -15523.219 x3 + 21510.163 x4 + -4036.921 x5 + -8593.732 x6 + 2479.501 x7 + 147.258 x8 + 5134.223 x9 + -4490.716 x10 + -4623.850 x11 + 5350.881 x12 + 5488.515 x13 + -7524.670 x14 + 1369.968 x15 + 9711.373 x16 + -23128.432 x17 + 19498.620 x18 + -5525.998 x19 + -0.103 u1 + 2345.301 x7 u0 + -5762.876 x8 u0 + 3635.515 x9 u0 + -1388.851 x17 u0 + 1672.547 x18 u0 + -501.636 x19 u0 + 0.001 x0 u0 u1 + 185.074 x14 u0^2 + -432.946 x15 u0^2 + 0.346 x16 u0 u1 + 763.891 x17 u0^2 + -0.514 x17 u0 u1 + -720.536 x18 u0^2 + 204.517 x19 u0^2 + 0.168 x19 u0 u1
x9' = 117.402 x1 + 3369.768 x2 + -15220.387 x3 + 21580.482 x4 + -5256.213 x5 + -10235.554 x6 + 2389.693 x7 + 1987.582 x8 + 6375.037 x9 + -4178.127 x10 + -5149.700 x11 + 3978.535 x12 + 4539.804 x13 + -7280.406 x14 + 1569.841 x15 + 11341.276 x16 + -21614.053 x17 + 15782.808 x18 + -4108.107 x19 + -0.103 u1 + 2199.602 x7 u0 + -5421.200 x8 u0 + 3431.871 x9 u0 + -1403.969 x17 u0 + 1729.028 x18 u0 + -535.333 x19 u0 + 0.001 x0 u0 u1 + 166.990 x14 u0^2 + -389.714 x15 u0^2 + 0.348 x16 u0 u1 + 684.316 x17 u0^2 + -0.517 x17 u0 u1 + -643.946 x18 u0^2 + 182.353 x19 u0^2 + 0.168 x19 u0 u1
x10' = -407.672 x1 + 5351.699 x2 + -17400.175 x3 + 21106.590 x4 + -4377.201 x5 + -8631.202 x6 + -797.989 x7 + 8692.704 x8 + 81.457 x9 + -3616.479 x10 + -4220.220 x11 + 3074.164 x12 + 4606.453 x13 + -3589.584 x14 + -2666.246 x15 + 8935.073 x16 + -12255.202 x17 + 8229.668 x18 + -2126.136 x19 + -0.103 u1 + 6.890 x8 u0 + -8.178 x9 u0 + 6.533 x18 u0 + -5.246 x19 u0 + 0.001 x0 u0 u1 + 82.076 x14 u0^2 + -180.790 x15 u0^2 + 0.114 x16 u0 u1 + 277.990 x17 u0^2 + -0.175 x17 u0 u1 + -242.506 x18 u0^2 + 63.230 x19 u0^2 + 0.060 x19 u0 u1
x11' = -1390.935 x1 + 6808.654 x2 + -16882.245 x3 + 21316.722 x4 + -5606.177 x5 + -10416.214 x6 + -599.379 x7 + 10084.241 x8 + 1602.765 x9 + -3459.622 x10 + -4783.965 x11 + 1953.936 x12 + 3766.591 x13 + -3885.014 x14 + -1931.693 x15 + 10772.826 x16 + -11863.044 x17 + 5451.711 x18 + -949.435 x19 + -0.103 u1 + 6.360 x8 u0 + -7.529 x9 u0 + 5.880 x18 u0 + -4.711 x19 u0 + 0.001 x0 u0 u1 + 76.801 x14 u0^2 + -169.600 x15 u0^2 + 0.141 x16 u0 u1 + 262.540 x17 u0^2 + -0.213 x17 u0 u1 + -230.043 x18 u0^2 + 60.301 x19 u0^2 + 0.072 x19 u0 u1
x12' = -2235.385 x1 + 8101.122 x2 + -16521.306 x3 + 21505.935 x4 + -6619.152 x5 + -11954.855 x6 + -370.538 x7 + 11221.384 x8 + 2891.880 x9 + -3366.138 x10 + -5233.690 x11 + 1031.126 x12 + 3079.555 x13 + -4144.467 x14 + -1398.453 x15 + 12346.549 x16 + -11432.429 x17 + 3027.968 x18 + 60.643 x19 + -0.102 u1 + 5.776 x8 u0 + -6.820 x9 u0 + 5.204 x18 u0 + -4.160 x19 u0 + 0.001 x0 u0 u1 + 71.077 x14 u0^2 + -157.429 x15 u0^2 + 0.160 x16 u0 u1 + 245.589 x17 u0^2 + -0.241 x17 u0 u1 + -216.265 x18 u0^2 + 57.028 x19 u0^2 + 0.080 x19 u0 u1
x13' = -2914.785 x1 + 9195.156 x2 + -16352.953 x3 + 21700.622 x4 + -7389.253 x5 + -13227.273 x6 + -105.101 x7 + 12086.947 x8 + 3913.208 x9 + -3364.415 x10 + -5569.193 x11 + 346.587 x12 + 2591.976 x13 + -4356.508 x14 + -1112.887 x15 + 13609.101 x16 + -10963.323 x17 + 1028.948 x18 + 872.921 x19 + -0.102 u1 + 5.142 x8 u0 + -6.056 x9 u0 + 4.512 x18 u0 + -3.598 x19 u0 + 64.845 x14 u0^2 + -144.115 x15 u0^2 + 0.172 x16 u0 u1 + 226.780 x17 u0^2 + -0.257 x17 u0 u1 + -200.803 x18 u0^2 + 53.293 x19 u0^2 + 0.085 x19 u0 u1
x14' = -3410.559 x1 + 10062.371 x2 + -16388.277 x3 + 21909.453 x4 + -7908.845 x5 + -14207.827 x6 + 210.215 x7 + 12662.850 x8 + 4635.473 x9 + -3471.237 x10 + -5789.330 x11 + -76.914 x12 + 2336.291 x13 + -4500.409 x14 + -1109.152 x15 + 14516.340 x16 + -10448.931 x17 + -498.004 x18 + 1466.296 x19 + -0.102 u1 + 4.459 x8 u0 + -5.239 x9 u0 + 3.812 x18 u0 + -3.032 x19 u0 + 57.996 x14 u0^2 + -129.379 x15 u0^2 + 0.174 x16 u0 u1 + 205.518 x17 u0^2 + -0.260 x17 u0 u1 + -183.044 x18 u0^2 + 48.909 x19 u0^2 + 0.086 x19 u0 u1
x15' = -3714.147 x1 + 10682.690 x2 + -16594.739 x3 + 22075.558 x4 + -8170.178 x5 + -14827.695 x6 + 583.006 x7 + 12893.368 x8 + 5026.033 x9 + -3660.976 x10 + -5868.114 x11 + -249.808 x12 + 2298.805 x13 + -4544.037 x14 + -1381.467 x15 + 15018.661 x16 + -9875.750 x17 + -1533.545 x18 + 1832.167 x19 + -0.102 u1 + 3.732 x8 u0 + -4.374 x9 u0 + 3.113 x18 u0 + -2.471 x19 u0 + 50.381 x14 u0^2 + -112.840 x15 u0^2 + 0.166 x16 u0 u1 + 181.009 x17 u0^2 + -0.248 x17 u0 u1 + -162.179 x18 u0^2 + 43.629 x19 u0^2 + 0.081 x19 u0 u1
x16' = -3823.479 x1 + 11062.086 x2 + -16975.077 x3 + 22142.389 x4 + -8128.381 x5 + -15023.069 x6 + 992.841 x7 + 12714.175 x8 + 5064.724 x9 + -3892.193 x10 + -5769.792 x11 + -187.624 x12 + 2443.189 x13 + -4472.414 x14 + -1898.825 x15 + 15089.996 x16 + -9252.710 x17 + -2062.869 x18 + 1966.895 x19 + -0.101 u1 + 2.964 x8 u0 + -3.468 x9 u0 + 2.426 x18 u0 + -1.922 x19 u0 + 41.892 x14 u0^2 + -94.216 x15 u0^2 + 0.147 x16 u0 u1 + 152.649 x17 u0^2 + -0.219 x17 u0 u1 + -137.585 x18 u0^2 + 37.260 x19 u0^2 + 0.072 x19 u0 u1
x17' = -3740.113 x1 + 11250.056 x2 + -17696.794 x3 + 22284.082 x4 + -7767.737 x5 + -14892.525 x6 + 1421.715 x7 + 12177.637 x8 + 4774.488 x9 + -4193.872 x10 + -5517.814 x11 + 132.495 x12 + 2798.766 x13 + -4320.438 x14 + -2700.232 x15 + 14820.312 x16 + -8629.082 x17 + -2087.610 x18 + 1876.566 x19 + -0.101 u1 + 2.161 x8 u0 + -2.527 x9 u0 + 1.761 x18 u0 + -1.395 x19 u0 + 32.429 x14 u0^2 + -73.247 x15 u0^2 + 0.115 x16 u0 u1 + 119.884 x17 u0^2 + -0.171 x17 u0 u1 + -108.693 x18 u0^2 + 29.627 x19 u0^2 + 0.056 x19 u0 u1
x18' = -3413.665 x1 + 10876.834 x2 + -18142.145 x3 + 22444.514 x4 + -7382.164 x5 + -14632.939 x6 + 1909.977 x7 + 11667.954 x8 + 3888.526 x9 + -4286.674 x10 + -5196.219 x11 + 622.172 x12 + 3252.142 x13 + -4346.391 x14 + -3295.814 x15 + 14436.001 x16 + -8531.919 x17 + -1475.007 x18 + 1594.750 x19 + -0.101 u1 + 98.880 x8 u0 + -236.718 x9 u0 + 144.964 x10 u0 + -24.933 x18 u0 + 17.807 x19 u0 + 29.318 x14 u0^2 + -68.098 x15 u0^2 + 0.087 x16 u0 u1 + 118.510 x17 u0^2 + -0.130 x17 u0 u1 + -111.068 x18 u0^2 + 31.337 x19 u0^2 + 0.042 x19 u0 u1
x19' = -2477.091 x1 + 8523.814 x2 + -15086.958 x3 + 18076.155 x4 + -5626.720 x5 + -11140.969 x6 + 1975.669 x7 + 8379.812 x8 + 2857.064 x9 + -3851.560 x10 + -3761.996 x11 + 852.877 x12 + 2979.435 x13 + -2908.884 x14 + -3821.581 x15 + 10735.090 x16 + -5528.999 x17 + -1315.920 x18 + 1130.735 x19 + -0.100 u1 + 0.490 x8 u0 + -0.588 x9 u0 + 0.531 x18 u0 + -0.433 x19 u0 + 9.811 x14 u0^2 + -22.283 x15 u0^2 + 36.928 x17 u0^2 + 0.012 x17 u0 u1 + -33.713 x18 u0^2 + -0.026 x18 u0 u1 + 9.257 x19 u0^2 + 0.014 x19 u0 u1`

Unfortunately I don't have a closed form solution of my ground truth model as it is a multibody system developed in a software called Simpack for multibody dynamic analysis.

The derivatives seem very reasonable using visual inspection:
![20DOF_derivatives](https://user-images.githubusercontent.com/53335430/96468878-e254c780-122c-11eb-846d-797a0953d1b1.png)

Do you think using another more stable integrator (not so sensitive to errors) would solve this problem? if so, I am not able to use any other integrator from `scipy.integrate` in `simulate()` function.

Thanks,
Omar

**Comment by akaptano** [comment] 2020-10-19 15:27
Omar, it looks like x1dot has some deviations from the ground truth. However, even if all of the derivatives look very good by inspection, the problem of small numerical errors to the ground truth remains. This will not be fixed by a better integrator because the issue is that the _model itself is almost certainly unstable_. Moreover, you are almost certainly overfitting with such a large model -- do you get similar results with the sparsity parameter increased or using only the first 5-10 PCA modes? 

There are a number of ways to address the stability issue:
1. Attempt a stability analysis (this may be quite hard with a 20-dimensional state space). You could begin by just considering the matrix of linear terms and see if the linear piece is stable.
2. Increase the sparsity or decrease the number of PCA modes. Typically the more terms in the solved equations, the more ways a system can be made unstable.  
3. Implement SINDy with constraints that guarantee certain properties of stability/energy conservation otherwise. 
4. Use more sophisticated SINDy algorithms. 

If you would like, I can email you my recent plasma physics paper which does something very similar: reduces the DOFs using the proper orthogonal decomposition, builds a model for their evolution with SINDy, and constrains the SINDy structure with conservation of energy. There is also a long discussion of stability in the conclusion.

**Comment by okamel1** [comment] 2020-10-19 15:52
Hi Alan,
Thanks for your suggestions. I'll try them and comment back with my results. 
It would be great to have a look at your paper, my email is: omar.kamel@tum.de

**Comment by briandesilva** [comment] 2021-06-05 20:03
I think the `TrappingSINDy` algorithm implemented in #106 might help. I'm closing this issue for now due to inactivity. If new progress is made, feel free to reopen it.

**Comment by fahim831** [comment] 2022-01-13 10:16
> There are a number of ways to address the stability issue:
> 1. Attempt a stability analysis (this may be quite hard with a 20-dimensional state space). You could begin by just considering the matrix of linear terms and see if the linear piece is stable.
> 2. Increase the sparsity or decrease the number of PCA modes. Typically the more terms in the solved equations, the more ways a system can be made unstable.
> 3. Implement SINDy with constraints that guarantee certain properties of stability/energy conservation otherwise.
> 4. Use more sophisticated SINDy algorithms.

I ran into a similar problem for weeks now and suspect, after trying many things, that this is the issue. Has there been any progress with this sensitivity and instability of models? I can understand 20 variables being too many, but I am only considering 5 (and 1 forced input u) and am not able to use model.simulate() after identifying the model, despite amazing model.score() values above 0.99.

Do you think such issues can be caused by scaling since I wasn't able to identify a model in my original space (orders of magnitudes from 10^6 to 10^-2), so I used the StandardScaler. The issue is similar to what is described in this thread. When I just feed my unseen test trajectory to the model exactly, it's **perfect**. However, if I change it even very slightly, so little that it's almost indistinguishable visually, the derivatives are very different and zig-zagged. This causes the integration to blow up very quickly.

I read the answer about using PCA/POD. However, for only 5 variables, I think PCA sounds like overkill. So I was wondering if you could explain in a bit more detail what you mean by #4, _more sophisticated SINDy algorithms_?

My model for x0 (mislabeled x1 in figure), which I have shown in the plot below is

`(x0)' = 0.620 1 + 23.853 x0 + 20.643 x1 + -0.242 x3 + -2.831 x4 + -0.538 x0^2 + 3.816 x1^2 + -5.838 x3^2 + 1.944 x4^2 + 0.725 u0`

![Untitled](https://user-images.githubusercontent.com/44279032/149310795-6d742b4e-1e09-4bca-8587-12f612db3f52.png)

**Comment by akaptano** [comment] 2022-01-13 17:00
This could be a lot of things. It could be a scaling issue, it could be your system is very sensitive, etc. If you post or email the code I can take a look and get back to you. Is there a "ground truth" model or is there experimental data? If there is a "true model", how close does SINDy get to this? 

More sophisticated SINDy algorithms would mean either using (in)equality constraints to add some physical priors that you know, or using our recent work with "Trapping SINDy". Basically if the system is quadratic (yours is) AND the system's nonlinearities preserve the energy, you can use this variant of SINDy to build provably globally stable models. I have no idea if this applies to you but if you send more information about the dynamical system you are looking at, I can try and give you some options.

**Comment by fahim831** [comment] 2022-01-13 20:45
I think we can discuss some of the details and explain it better via email as you suggest. Can you provide your email address?

**Comment by akaptano** [comment] 2022-01-13 21:08
Yes, feel free to email me at alanakaptanoglu@gmail.com.

**Closed** 2022-02-10 16:35 UTC
